import argparse
import json
import math
import os
import re
import subprocess
import time
from pathlib import Path

import numpy as np
import torch
from safetensors.torch import load_file, save_file

FRAMEWORK_ROOT = Path(__file__).resolve().parent
PROJECT_ROOT = FRAMEWORK_ROOT.parent
ZIPSERV_ROOT = FRAMEWORK_ROOT / "ZipServ_ASPLOS26"
BUILD_DIR = ZIPSERV_ROOT / "build"
BENCH_DIR = ZIPSERV_ROOT / "kernel_benchmark"
HELPER_SRC = BENCH_DIR / "kv_decompress_from_blob.cu"
HELPER_BIN = BENCH_DIR / "kv_decompress_from_blob"


def run_cmd(cmd, cwd=None, env=None):
    result = subprocess.run(
        cmd,
        cwd=cwd,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Command failed ({result.returncode}): {' '.join(cmd)}\\n{result.stdout}"
        )
    return result.stdout


def ensure_zipserv_built():
    if not BUILD_DIR.exists():
        raise FileNotFoundError(BUILD_DIR)
    run_cmd(["make"], cwd=BUILD_DIR)


def ensure_helper_built():
    if not HELPER_SRC.exists():
        raise FileNotFoundError(HELPER_SRC)

    cmd = [
        "nvcc",
        "-O3",
        "--std=c++14",
        "-gencode",
        "arch=compute_80,code=sm_80",
        "-I/usr/local/cuda/include",
        "-I../build",
        "-L../build",
        "-lL_API",
        "-lcublas",
        "-lcusparse",
        "-Xlinker",
        "-rpath,$ORIGIN/../build",
        str(HELPER_SRC.name),
        "-o",
        str(HELPER_BIN.name),
    ]
    run_cmd(cmd, cwd=BENCH_DIR)


def choose_kv_tensors(tensors, tensor_regex, max_tensors):
    keys = [name for name in tensors.keys() if ".key" in name or ".value" in name]
    if tensor_regex:
        pat = re.compile(tensor_regex)
        keys = [name for name in keys if pat.search(name)]
    if max_tensors > 0:
        keys = keys[:max_tensors]
    return keys


def parse_helper_output(text: str):
    stats = {}
    for line in text.splitlines():
        if "=" in line:
            k, v = line.strip().split("=", 1)
            stats[k] = v
    return stats


def u16_numpy_to_bf16_tensor(arr: np.ndarray) -> torch.Tensor:
    i16 = arr.view(np.int16)
    return torch.from_numpy(i16.copy()).view(torch.bfloat16)


def decompress_one_tensor(entry, original_tensor: torch.Tensor, tmp_dir: Path, gpu_id: int):
    blob_path = Path(entry["blob"]).resolve()
    if not blob_path.exists():
        raise FileNotFoundError(blob_path)

    packed_shape = entry["packed_shape"]
    orig_shape = entry["orig_shape"]
    orig_rows = int(entry["orig_rows"])
    orig_cols = int(entry["orig_cols"])

    if len(packed_shape) != 2:
        raise ValueError(f"Invalid packed_shape for {entry['tensor']}: {packed_shape}")

    safe_name = entry["tensor"].replace("/", "_").replace(".", "_")
    output_bin = tmp_dir / f"{safe_name}.decompressed.u16.bin"

    env = os.environ.copy()
    env["LD_LIBRARY_PATH"] = f"{BUILD_DIR}:{env.get('LD_LIBRARY_PATH', '')}"
    env["CUDA_VISIBLE_DEVICES"] = str(gpu_id)

    out = run_cmd(
        [
            str(HELPER_BIN),
            str(blob_path),
            str(output_bin),
        ],
        cwd=BENCH_DIR,
        env=env,
    )

    arr_u16 = np.fromfile(output_bin, dtype=np.uint16)
    expected = int(packed_shape[0]) * int(packed_shape[1])
    if arr_u16.size != expected:
        raise ValueError(
            f"Decompressed size mismatch for {entry['tensor']}: expected={expected}, got={arr_u16.size}"
        )

    arr_u16 = arr_u16.reshape(int(packed_shape[0]), int(packed_shape[1]))
    out_tensor_padded = u16_numpy_to_bf16_tensor(arr_u16)
    out_tensor = out_tensor_padded[:orig_rows, :orig_cols].reshape(orig_shape).contiguous()

    same_shape = tuple(out_tensor.shape) == tuple(original_tensor.shape)
    same_dtype = out_tensor.dtype == original_tensor.dtype
    same_tensor = bool(torch.equal(out_tensor, original_tensor)) if (same_shape and same_dtype) else False

    helper_stats = parse_helper_output(out)
    return {
        "tensor": entry["tensor"],
        "status": "ok",
        "gpu": gpu_id,
        "blob": str(blob_path),
        "decompress_ms": float(helper_stats.get("decompress_ms", "nan")),
        "same_shape": same_shape,
        "same_dtype": same_dtype,
        "same_tensor": same_tensor,
        "tensor_out": out_tensor,
    }


def main():
    parser = argparse.ArgumentParser(description="ZipServ KV cache decompression framework")
    parser.add_argument("--input", required=True, type=Path, help="original input safetensors")
    parser.add_argument("--manifest", required=True, type=Path, help="manifest generated by compress framework")
    parser.add_argument("--output", type=Path, default=None, help="restored safetensors path")
    parser.add_argument("--tmp-dir", type=Path, default=FRAMEWORK_ROOT / ".zipserv_tmp_decompress")
    parser.add_argument("--tensor-regex", type=str, default="")
    parser.add_argument("--max-tensors", type=int, default=0)
    parser.add_argument("--cuda-device", type=int, default=0)
    parser.add_argument("--skip-verify", action="store_true", help="skip equality check against original")
    args = parser.parse_args()

    if not args.input.exists():
        raise FileNotFoundError(args.input)
    if not args.manifest.exists():
        raise FileNotFoundError(args.manifest)

    args.tmp_dir.mkdir(parents=True, exist_ok=True)

    ensure_zipserv_built()
    ensure_helper_built()

    with args.manifest.open("r", encoding="utf-8") as f:
        manifest = json.load(f)

    original_tensors = load_file(str(args.input))
    selected = choose_kv_tensors(original_tensors, args.tensor_regex, args.max_tensors)
    if not selected:
        raise ValueError("No KV tensors matched")

    manifest_entries = {
        item["tensor"]: item
        for item in manifest.get("results", [])
        if item.get("status") == "ok"
    }

    restored_tensors = {k: v for k, v in original_tensors.items()}
    results = []

    wall_start = time.perf_counter()
    for name in selected:
        if name not in manifest_entries:
            raise ValueError(f"Tensor {name} missing in manifest ok results")

        entry = manifest_entries[name]
        if str(entry.get("dtype", "")) != "torch.bfloat16":
            raise ValueError(f"Tensor {name} dtype in manifest is not torch.bfloat16")

        original_tensor = original_tensors[name]
        res = decompress_one_tensor(entry, original_tensor, args.tmp_dir, args.cuda_device)
        restored_tensors[name] = res.pop("tensor_out")
        results.append(res)

        print(
            f"ok tensor={name} gpu={args.cuda_device} decompress_ms={res['decompress_ms']:.3f} "
            f"same_tensor={res['same_tensor']}"
        )

    wall_end = time.perf_counter()

    if args.output is None:
        args.output = args.input.with_suffix(".zipserv.restored.safetensors")

    save_file(restored_tensors, str(args.output), metadata={
        "source_input": str(args.input),
        "source_manifest": str(args.manifest),
        "num_selected": str(len(selected)),
    })

    verify_failed = [
        r for r in results
        if not (r.get("same_shape") and r.get("same_dtype") and r.get("same_tensor"))
    ]

    wall_ms = (wall_end - wall_start) * 1000.0
    avg_decompress_ms = (
        sum(r.get("decompress_ms", 0.0) for r in results) / len(results)
        if results
        else float("nan")
    )

    print("=== summary ===")
    print(f"output={args.output}")
    print(f"num_selected={len(selected)}")
    print(f"num_ok={len(results)}")
    print(f"avg_decompress_ms={avg_decompress_ms:.3f}")
    print(f"wall_time_ms={wall_ms:.3f}")
    print(f"verify_failed={len(verify_failed)}")

    if verify_failed and not args.skip_verify:
        raise SystemExit(2)


if __name__ == "__main__":
    main()
